### ISSUE TITLE
Pip hack script fails with --extra-index-url option

### ISSUE THREAD

**Issue by a1russell** [poise/poise-python#10]
Running into a problem where I think the `PIP_HACK_SCRIPT` is failing due to an `--extra-index-url` option given in the `options` property. My resource looks similar to:

    python_package 'tinydb' do
      version '2.4'
      virtualenv my_venv_dir
      options '--extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple'
    end

Running the cookbook gives me this stacktrace:

    ...<snip>...
    [2015-10-08T09:20:55-04:00] DEBUG: [python_package[tinydb]] Running python command: /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4
    Exception:
    Traceback (most recent call last):
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/basecommand.py", line 211, in main
        status = self.run(options, args)
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 95, in run
        self.run_outdated(options)
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 104, in run_outdated
        for dist, version, typ in self.find_packages_latest_versions(options):
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 119, in find_packages_latest_versions
        user_only=options.user):
      File "<stdin>", line 16, in replacement
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
        reqs = list(parse_requirements(s))
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
        "version spec")
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
        raise RequirementParseError(msg, line, "at", line[p:])
    pip._vendor.pkg_resources.RequirementParseError: Expected version spec in http://artifactory.example.com/api/pypi/my-repo/simple at ://artifactory.example.com/api/pypi/my-repo/simple
    
    
        ================================================================================
        Error executing action `install` on resource 'python_package[tinydb]'
        ================================================================================
    
        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '2'
        ---- Begin output of /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 ----
        STDOUT:
        STDERR: Exception:
        Traceback (most recent call last):
          File "/opt/my-venv/lib64/python3.4/site-packages/pip/basecommand.py", line 211, in main
            status = self.run(options, args)
          File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 95, in run
            self.run_outdated(options)
          File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 104, in run_outdated
            for dist, version, typ in self.find_packages_latest_versions(options):
          File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 119, in find_packages_latest_versions
            user_only=options.user):
          File "<stdin>", line 16, in replacement
          File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
            reqs = list(parse_requirements(s))
          File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
            "version spec")
          File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
            raise RequirementParseError(msg, line, "at", line[p:])
        pip._vendor.pkg_resources.RequirementParseError: Expected version spec in http://artifactory.example.com/api/pypi/my-repo/simple at ://artifactory.example.com/api/pypi/my-repo/simple
        ---- End output of /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 ----
        Ran /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 returned 2
    
        Cookbook Trace:
        ---------------
        /home/me/chef-repo/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:206:in `tap'
        /home/me/chef-repo/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:206:in `language_command_shell_out!'
        /home/me/chef-repo/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:221:in `block in language_command_mixin'
        /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:260:in `pip_command'
        /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:284:in `pip_outdated'
        /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:166:in `check_package_versions'
        /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:146:in `load_current_resource'
    
        Resource Declaration:
        ---------------------
        # In /home/me/chef-repo/cookbooks/my-cookbook/recipes/default.rb
    
         34: python_package 'tinydb' do
         35:   version '2.4'
         36:   virtualenv my_venv_dir
         37:   options '--extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple'
         38: end
         39:
    
        Compiled Resource:
        ------------------
        # Declared in /home/me/chef-repo/cookbooks/my-cookbook/recipes/default.rb:34:in `from_file'
    
        python_package("tinydb") do
          action :install
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          options "--extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple"
          package_name "tinydb"
          version "2.4"
          timeout 900
          declared_type :python_package
          cookbook_name :"my-cookbook"
          recipe_name "default"
          parent_python python_virtualenv[/opt/my-venv]
        end
    
    [2015-10-08T09:20:56-04:00] INFO: Running queued delayed notifications before re-raising exception
    [2015-10-08T09:20:56-04:00] DEBUG: Re-raising exception: Mixlib::ShellOut::ShellCommandFailed - python_package[tinydb] (my-cookbook::default line 34) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
    ---- Begin output of /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 ----
    STDOUT:
    STDERR: Exception:
    Traceback (most recent call last):
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/basecommand.py", line 211, in main
        status = self.run(options, args)
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 95, in run
        self.run_outdated(options)
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 104, in run_outdated
        for dist, version, typ in self.find_packages_latest_versions(options):
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 119, in find_packages_latest_versions
        user_only=options.user):
      File "<stdin>", line 16, in replacement
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
        reqs = list(parse_requirements(s))
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
        "version spec")
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
        raise RequirementParseError(msg, line, "at", line[p:])
    pip._vendor.pkg_resources.RequirementParseError: Expected version spec in http://artifactory.example.com/api/pypi/my-repo/simple at ://artifactory.example.com/api/pypi/my-repo/simple
    ---- End output of /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 ----
    Ran /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 returned 2
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout.rb:289:in `invalid!'
      /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout.rb:276:in `error!'
      /home/me/chef-repo/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:206:in `tap'
      /home/me/chef-repo/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:206:in `language_command_shell_out!'
      /home/me/chef-repo/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:221:in `block in language_command_mixin'
      /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:260:in `pip_command'
      /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:284:in `pip_outdated'
      /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:166:in `check_package_versions'
      /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:146:in `load_current_resource'
      /opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:113:in `run_action'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
      /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
      /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
      /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:457:in `run'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
      /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
      /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:60:in `run'
      /opt/chefdk/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
      /opt/chefdk/bin/chef-solo:51:in `load'
      /opt/chefdk/bin/chef-solo:51:in `<main>'
    
    Running handlers:
    [2015-10-08T09:20:56-04:00] ERROR: Running exception handlers
    Running handlers complete
    [2015-10-08T09:20:56-04:00] ERROR: Exception handlers complete
    [2015-10-08T09:20:56-04:00] FATAL: Stacktrace dumped to /home/me/chef-solo/chef-stacktrace.out
    [2015-10-08T09:20:56-04:00] DEBUG: Mixlib::ShellOut::ShellCommandFailed: python_package[tinydb] (my-cookbook::default line 34) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
    ---- Begin output of /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 ----
    STDOUT:
    STDERR: Exception:
    Traceback (most recent call last):
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/basecommand.py", line 211, in main
        status = self.run(options, args)
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 95, in run
        self.run_outdated(options)
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 104, in run_outdated
        for dist, version, typ in self.find_packages_latest_versions(options):
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 119, in find_packages_latest_versions
        user_only=options.user):
      File "<stdin>", line 16, in replacement
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
        reqs = list(parse_requirements(s))
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
        "version spec")
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
        raise RequirementParseError(msg, line, "at", line[p:])
    pip._vendor.pkg_resources.RequirementParseError: Expected version spec in http://artifactory.example.com/api/pypi/my-repo/simple at ://artifactory.example.com/api/pypi/my-repo/simple
    ---- End output of /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 ----
    Ran /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 returned 2
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout.rb:289:in `invalid!'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout.rb:276:in `error!'
    /home/me/chef-repo/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:206:in `tap'
    /home/me/chef-repo/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:206:in `language_command_shell_out!'
    /home/me/chef-repo/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:221:in `block in language_command_mixin'
    /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:260:in `pip_command'
    /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:284:in `pip_outdated'
    /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:166:in `check_package_versions'
    /home/me/chef-repo/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:146:in `load_current_resource'
    /opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:113:in `run_action'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
    /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
    /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
    /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
    /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
    /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
    /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
    /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
    /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
    /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
    /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
    /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:457:in `run'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
    /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
    /opt/chefdk/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
    /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:60:in `run'
    /opt/chefdk/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
    /opt/chefdk/bin/chef-solo:51:in `load'
    /opt/chefdk/bin/chef-solo:51:in `<main>'
    Chef Client failed. 6 resources updated in 29.366737526 seconds
    [2015-10-08T09:20:56-04:00] ERROR: python_package[tinydb] (my-cookbook::default line 34) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
    ---- Begin output of /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 ----
    STDOUT:
    STDERR: Exception:
    Traceback (most recent call last):
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/basecommand.py", line 211, in main
        status = self.run(options, args)
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 95, in run
        self.run_outdated(options)
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 104, in run_outdated
        for dist, version, typ in self.find_packages_latest_versions(options):
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/commands/list.py", line 119, in find_packages_latest_versions
        user_only=options.user):
      File "<stdin>", line 16, in replacement
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
        reqs = list(parse_requirements(s))
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
        "version spec")
      File "/opt/my-venv/lib64/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
        raise RequirementParseError(msg, line, "at", line[p:])
    pip._vendor.pkg_resources.RequirementParseError: Expected version spec in http://artifactory.example.com/api/pypi/my-repo/simple at ://artifactory.example.com/api/pypi/my-repo/simple
    ---- End output of /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 ----
    Ran /opt/my-venv/bin/python - list --extra-index-url http://artifactory.example.com/api/pypi/my-repo/simple --outdated tinydb\=\=2.4 returned 2
    [2015-10-08T09:20:56-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by a1russell** [comment]
Just noticed b5ce5ca128fc29483f8d5c617dac72795d749a7b. Is that an attempt to fix this? I'll try it out when I have some time.

**Comment by jrake-revelant** [comment]
I have a similar problem, however with a different error message.

When using 

```python_package 'falcon_web_oauth_request_proxy' do
  version '1.0.4'
  user 'oaproxy'
  virtualenv '/home/oaproxy/.env'
  options '--index-url https://artifactory.myartifactory.com/artifactory/api/pypi/pypi-virtual/simple'
  action :install
end````

I end upt with 
```No candidate version available for falcon_web_oauth_request_proxy````

Running the `pip install` manually with the option works fine. So does including it in `~/.pip/pip.conf` and omitting the command. However the same error presents itself during the chef run.

**Comment by coderanger** [comment]
Fixed in 1.1.1, which is now posted.

**Comment by jrake-revelant** [comment]
I know get a similar exception as the OP when using v 1.1.1:

```================================================================================
         Error executing action `install` on resource 'python_package[falcon_web_oauth_request_proxy]'
         ================================================================================

         Mixlib::ShellOut::ShellCommandFailed
         ------------------------------------
         Expected process to exit with [0], but received '2'
         ---- Begin output of /home/oaproxy/.env/bin/python - list --index-url https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple --outdated falcon_web_oauth_request_proxy\=\=1.0.4 ----
         STDOUT:
         STDERR: Exception:
         Traceback (most recent call last):
           File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
             status = self.run(options, args)
         File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/commands/list.py", line 95, in run
             self.run_outdated(options)
           File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/commands/list.py", line 104, in run_outdated
             for dist, version, typ in self.find_packages_latest_versions(options):

             user_only=options.user):
           File "<stdin>", line 18, in replacement
           File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
             reqs = list(parse_requirements(s))
           File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
             "version spec")
         File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
             raise RequirementParseError(msg, line, "at", line[p:])
         RequirementParseError: Expected version spec in https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple at ://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple
         The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
         ---- End output of /home/oaproxy/.env/bin/python - list --index-url https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple --outdated falcon_web_oauth_request_proxy\=\=1.0.4 ----
         Ran /home/oaproxy/.env/bin/python - list --index-url https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple --outdated falcon_web_oauth_request_proxy\=\=1.0.4 returned 2


         ---------------
         /tmp/kitchen/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:206:in `tap'
         /tmp/kitchen/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:206:in `language_command_shell_out!'
         /tmp/kitchen/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/command/mixin.rb:221:in `block in language_command_mixin'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:262:in `pip_command'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:286:in `pip_outdated'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:168:in `check_package_versions'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:148:in `load_current_resource'

         Resource Declaration:
         ---------------------
       # In /tmp/kitchen/cache/cookbooks/auth-request-proxy/recipes/default.rb

          31: python_package 'falcon_web_oauth_request_proxy' do
          32:   version '1.0.4'
          33:   user 'oaproxy'
          34:   virtualenv '/home/oaproxy/.env'
          35:   options '--index-url https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple'
          36:   action :install
          37: end

         Compiled Resource:
         ------------------


         python_package("falcon_web_oauth_request_proxy") do
           action [:install]
           retries 0
           retry_delay 2
         default_guard_interpreter :default
           options "--index-url https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple"
           package_name "falcon_web_oauth_request_proxy"
           version "1.0.4"
           declared_type :python_package
           cookbook_name "auth-request-proxy"
           recipe_name "default"
           user "oaproxy"
           parent_python python_virtualenv[/home/oaproxy/.env]
         end


       Running handlers:
       [2015-10-18T09:34:40+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-10-18T09:34:40+00:00] ERROR: Exception handlers complete
       Chef Client failed. 19 resources updated in 01 minutes 11 seconds
       [2015-10-18T09:34:40+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-10-18T09:34:40+00:00] ERROR: python_package[falcon_web_oauth_request_proxy] (auth-request-proxy::default line 31) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
       ---- Begin output of /home/oaproxy/.env/bin/python - list --index-url https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple --outdated falcon_web_oauth_request_proxy\=\=1.0.4 ----
       STDOUT:
       STDERR: Exception:
       Traceback (most recent call last):
         File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
           status = self.run(options, args)
         File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/commands/list.py", line 95, in run
           self.run_outdated(options)
         File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/commands/list.py", line 104, in run_outdated
           for dist, version, typ in self.find_packages_latest_versions(options):
         File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/commands/list.py", line 119, in find_packages_latest_versions
           user_only=options.user):
         File "<stdin>", line 18, in replacement
         File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
           reqs = list(parse_requirements(s))
         File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
           "version spec")
         File "/home/oaproxy/.env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
           raise RequirementParseError(msg, line, "at", line[p:])
       RequirementParseError: Expected version spec in https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple at ://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple
       The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
       ---- End output of /home/oaproxy/.env/bin/python - list --index-url https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple --outdated falcon_web_oauth_request_proxy\=\=1.0.4 ----
       Ran /home/oaproxy/.env/bin/python - list --index-url https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple --outdated falcon_web_oauth_request_proxy\=\=1.0.4 returned 2
       [2015-10-18T09:34:41+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
>>>>>> ----------------------```

**Comment by coderanger** [comment]
Try `options "--index-url=https://artifactory.falcon.eu.com/artifactory/api/pypi/pypi-virtual/simple"`. I need to improve the parsing but for now it just ignore any option that starts with `-`.
