### ISSUE TITLE
' can't modify frozen Array' on chef 14.3.37

### ISSUE THREAD

**Issue by scopenco** [poise/poise-python#124]
I got this issue on Chef 14.3.37

```
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/poise-python/libraries/default.rb
       ================================================================================

       FrozenError
       -----------
       can't modify frozen Array

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:220:in `included'
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:51:in `include'
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:51:in `poise_subresource_container'
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise.rb:93:in `block in Poise'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:34:in `include'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:34:in `<class:Resource>'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:33:in `<module:PythonRuntime>'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:25:in `<module:Resources>'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:22:in `<module:PoisePython>'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime.rb:21:in `<top (required)>'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources.rb:19:in `<top (required)>'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/cheftie.rb:17:in `<top (required)>'
         /tmp/kitchen/cache/cookbooks/poise-python/libraries/default.rb:19:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subresources/container.rb:

       213:                @container_default
       214:              end
       215:            end
       216:
       217:            def included(klass)
       218:              super
       219:              klass.extend(ClassMethods)
       220>>             klass.const_get(:HIDDEN_IVARS) << :@subcontexts
       221:              klass.const_get(:FORBIDDEN_IVARS) << :@subcontexts
       222:            end
       223:          end
       224:
       225:          extend ClassMethods
       226:        end
       227:      end
       228:    end
       229:  end
```

**Comment by coderanger** [comment]
This was fixed in Poise already. Please always check that you are up to date on cookbooks before filing bug reports.

**Comment by scopenco** [comment]
thank you!
