### ISSUE TITLE
ImportError: cannot import name 'sysconfig' poise

### ISSUE THREAD

**Issue by pleycpl** [poise/poise-python#127]
```
# .kitchen.yml
platforms:
  - name: ubuntu-18.04
```
```ruby
python_runtime 'cesi' do
  version '3.6'
  options :system
end
```
```bash
$ kitchen converge
...
* python_runtime[cesi] action install
           * poise_languages_system[python3.6] action install
       (up to date)
           * apt_package[python3.6, python3.6-dev] action nothing (skipped due to action :nothing)
            (up to date)
         * python_runtime_pip[cesi] action install
           
           ================================================================================
           Error executing action `install` on resource 'python_runtime_pip[cesi]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] ----
           STDOUT: 
           STDERR: Traceback (most recent call last):
             File "/tmp/get-pip20180725-24667-1p877fi.py", line 20651, in <module>
        main()
             File "/tmp/get-pip20180725-24667-1p877fi.py", line 197, in main
        bootstrap(tmpdir=tmpdir)
             File "/tmp/get-pip20180725-24667-1p877fi.py", line 82, in bootstrap
        import pip._internal
             File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/__init__.py", line 42, in <module>
             File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/cmdoptions.py", line 16, in <module>
             File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/index.py", line 24, in <module>
             File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/download.py", line 34, in <module>
             File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/locations.py", line 10, in <module>
           ImportError: cannot import name 'sysconfig'
           ---- End output of ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] ----
           Ran ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] returned 1
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/utils/shell_out.rb:86:in `tap'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/utils/shell_out.rb:86:in `poise_shell_out!'
           /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime_pip.rb:152:in `block in bootstrap_pip'
           /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime_pip.rb:128:in `bootstrap_pip'
           /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime_pip.rb:90:in `action_install'
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
           /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:50:in `action_install'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb
           
           118:         python_runtime_pip new_resource.name do
           119:           parent new_resource
           120:           # If the version is `true`, don't pass it at all.
           121:           version pip_version if pip_version.is_a?(String)
           122:           get_pip_url pip_url
           123:         end
           124:       end
           125: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:118:in `install_pip'
           
           python_runtime_pip("cesi") do
             action [:install]
             default_guard_interpreter :default
             declared_type :python_runtime_pip
             cookbook_name "cesi-cookbook"
             parent python_runtime[cesi]
             get_pip_url "https://bootstrap.pypa.io/get-pip.py"
           end
           
           System Info:
           ------------
           chef_version=14.3.37
           platform=ubuntu
           platform_version=18.04
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
           
         
         ================================================================================
         Error executing action `install` on resource 'python_runtime[cesi]'
         ================================================================================
         
         Mixlib::ShellOut::ShellCommandFailed
         ------------------------------------
         python_runtime_pip[cesi] (/tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb line 118) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
         ---- Begin output of ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] ----
         STDOUT: 
         STDERR: Traceback (most recent call last):
           File "/tmp/get-pip20180725-24667-1p877fi.py", line 20651, in <module>
             main()
           File "/tmp/get-pip20180725-24667-1p877fi.py", line 197, in main
             bootstrap(tmpdir=tmpdir)
           File "/tmp/get-pip20180725-24667-1p877fi.py", line 82, in bootstrap
             import pip._internal
           File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/__init__.py", line 42, in <module>
           File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/cmdoptions.py", line 16, in <module>
           File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/index.py", line 24, in <module>
           File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/download.py", line 34, in <module>
           File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/locations.py", line 10, in <module>
         ImportError: cannot import name 'sysconfig'
         ---- End output of ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] ----
         Ran ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] returned 1
         
         Cookbook Trace:
         ---------------
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/utils/shell_out.rb:86:in `tap'
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/utils/shell_out.rb:86:in `poise_shell_out!'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime_pip.rb:152:in `block in bootstrap_pip'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime_pip.rb:128:in `bootstrap_pip'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime_pip.rb:90:in `action_install'
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:50:in `action_install'
         
         Resource Declaration:
         ---------------------
         # In /tmp/kitchen/cache/cookbooks/cesi-cookbook/recipes/default.rb
         
          60: python_runtime 'cesi' do
          61:   version '3.6'
          62:   options :system
          63: end
          64: python_virtualenv "#{cesi_path}/.env"
         
         Compiled Resource:
         ------------------
         # Declared in /tmp/kitchen/cache/cookbooks/cesi-cookbook/recipes/default.rb:60:in `from_file'
         
         python_runtime("cesi") do
           action [:install]
           default_guard_interpreter :default
           subresources [python_virtualenv[/opt/cesi/.env], python_runtime_pip[cesi], python_package[setuptools], python_package[wheel]]
           declared_type :python_runtime
           cookbook_name "cesi-cookbook"
           recipe_name "default"
           version "3.6"
           get_pip_url "https://bootstrap.pypa.io/get-pip.py"
           pip_version true
           setuptools_version true
           virtualenv_version true
           wheel_version true
         end
         
         System Info:
         ------------
         chef_version=14.3.37
         platform=ubuntu
         platform_version=18.04
         ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
         program_name=/opt/chef/bin/chef-client
         executable=/opt/chef/bin/chef-client
         
       
       Running handlers:
       [2018-07-25T09:17:11+00:00] ERROR: Running exception handlers
       [2018-07-25T09:17:11+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-07-25T09:17:11+00:00] ERROR: Exception handlers complete
       [2018-07-25T09:17:11+00:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 05 seconds
       [2018-07-25T09:17:11+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-07-25T09:17:11+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-07-25T09:17:11+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-07-25T09:17:11+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-07-25T09:17:11+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: python_runtime[cesi] (cesi-cookbook::default line 60) had an error: Mixlib::ShellOut::ShellCommandFailed: python_runtime_pip[cesi] (/tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb line 118) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] ----
       STDOUT: 
       STDERR: Traceback (most recent call last):
         File "/tmp/get-pip20180725-24667-1p877fi.py", line 20651, in <module>
           main()
         File "/tmp/get-pip20180725-24667-1p877fi.py", line 197, in main
           bootstrap(tmpdir=tmpdir)
         File "/tmp/get-pip20180725-24667-1p877fi.py", line 82, in bootstrap
           import pip._internal
         File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/__init__.py", line 42, in <module>
         File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/cmdoptions.py", line 16, in <module>
         File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/index.py", line 24, in <module>
         File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/download.py", line 34, in <module>
         File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/locations.py", line 10, in <module>
       ImportError: cannot import name 'sysconfig'
       ---- End output of ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] ----
       Ran ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] returned 1
       [2018-07-25T09:17:11+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: python_runtime[cesi] (cesi-cookbook::default line 60) had an error: Mixlib::ShellOut::ShellCommandFailed: python_runtime_pip[cesi] (/tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb line 118) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] ----
       STDOUT: 
       STDERR: Traceback (most recent call last):
         File "/tmp/get-pip20180725-24667-1p877fi.py", line 20651, in <module>
           main()
         File "/tmp/get-pip20180725-24667-1p877fi.py", line 197, in main
           bootstrap(tmpdir=tmpdir)
         File "/tmp/get-pip20180725-24667-1p877fi.py", line 82, in bootstrap
           import pip._internal
         File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/__init__.py", line 42, in <module>
         File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/cmdoptions.py", line 16, in <module>
         File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/index.py", line 24, in <module>
         File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/download.py", line 34, in <module>
         File "/tmp/tmpw2n018fv/pip.zip/pip/_internal/locations.py", line 10, in <module>
       ImportError: cannot import name 'sysconfig'
       ---- End output of ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] ----
       Ran ["/usr/bin/python3.6", "/tmp/get-pip20180725-24667-1p877fi.py", "--upgrade", "--force-reinstall"] returned 1
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1804>.  Please see .kitchen/logs/default-ubuntu-1804.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

https://github.com/pypa/pip/issues/5367#issuecomment-386864941

**Comment by coderanger** [comment]
Fixed back in https://github.com/poise/poise-python/commit/861bf06e69131510c49fa5e35869bdba9fb7aabd
