### ISSUE TITLE
user specific virtualenv

### ISSUE THREAD

**Issue by jrake-revelant** [poise/poise-python#17]
Hi,

I am trying to use a user specific virtualenv:

```ruby
include_recipe 'poise-python'

service = 's3cmd'

user service do
  system true
  supports manage_home: true
end

python_virtualenv "/home/#{service}/.env2" do
  user service
end
```

however I get the following error: 

```bash
       Recipe: falcon-s3cmd::default
         * user[s3cmd] action create (up to date)
         * python_virtualenv[/home/s3cmd/.env2] action create

           ================================================================================
           Error executing action `create` on resource 'python_virtualenv[/home/s3cmd/.env2]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of ["/usr/bin/python2.7", "-m", "virtualenv", "/home/s3cmd/.env2"] ----
           STDOUT:
           STDERR: Traceback (most recent call last):
             File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
             File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
             File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2363, in <module>
        main()
             File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 832, in main
        symlink=options.symlink)
             File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 994, in create_environment
        site_packages=site_packages, clear=clear, symlink=symlink))
             File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1170, in install_python
        mkdir(lib_dir)
             File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 448, in mkdir
        os.makedirs(path)
             File "/usr/lib/python2.7/os.py", line 150, in makedirs

             File "/usr/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
             File "/usr/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
           OSError: [Errno 13] Permission denied: '/home/s3cmd/.env2'
           ---- End output of ["/usr/bin/python2.7", "-m", "virtualenv", "/home/s3cmd/.env2"] ----
           Ran ["/usr/bin/python2.7", "-m", "virtualenv", "/home/s3cmd/.env2"] returned 1
```

Omitting the user works fine but then the virtualenv is owned by `root` which produces other problems within the virtualenv such as this:

```shell
The directory '/home/s3cmd/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

What am I doing wrong?

Cheers
Jannis

**Comment by coderanger** [comment]
Check the actual file permissions on `/home/s3cmd`?

**Comment by bradchoate** [comment]
Having the same issue with pip_requirements. The user/group options aren't available for it, so packages wind up being owned by root instead of the user I want.

**Comment by coderanger** [comment]
@bradchoate user/group support for pip_requirements is now available in master. No idea why I didn't do that from the start. Will be part of the next release.

**Comment by coderanger** [comment]
`pip_requirements` user/group released in `poise-python` 1.2.0. Going to close this unless the original poster can provide more info.

**Comment by emoreth** [comment]
I had the same error, pip_requirements now accepts user and group, but entire virtualenv remains on root:root

**Comment by emoreth** [comment]
Better testing:

Suppose a virtualenv at /var/virtualenvs/MyVirtualenv

If /var/virtualenvs does not exists it will be created for root:root regardless user and group, and the MyVirtualenv will raise error of no writing permission...

If I manually create /var/virtualenvs before, MyVirtualenv creates fine, but at some point of my pip_requirements and python_package (both with user and group) I ended with some files/olders user:user and some root:root. Mostly pip, wheel and setuptools.

**Comment by coderanger** [comment]
@emoreth Please include your exact recipe code and cookbook versions.

**Comment by jrake-revelant** [comment]
Still persists sorry:

```
      Preparing to unpack .../chef_12.6.0-1_amd64.deb ...
       Unpacking chef (12.6.0-1) ...
       Setting up chef (12.6.0-1) ...
       Thank you for installing Chef!
       Transferring files to <default-ubuntu-1404>
       Starting Chef Client, version 12.6.0
       Creating a new client identity for default-ubuntu-1404 using the validator key.
       resolving cookbooks for run list: ["falcon-s3cmd::default"]
       Synchronizing Cookbooks:
         - falcon-s3cmd (0.1.0)
         - poise-python (1.2.0)
         - poise (2.5.0)
         - poise-languages (1.3.1)
       Compiling Cookbooks...
       Converging 4 resources
       Recipe: poise-python::default
         * python_runtime[2] action install
           * poise_languages_system[python2.7] action install
             - install version 2.7.6-8 of package python2.7-dev

         * python_runtime_pip[2] action install


           - install version 19.4 of package setuptools

           - install version 0.26.0 of package wheel

           - install version 13.1.2 of package virtualenv

       Recipe: falcon-s3cmd::default
         * user[s3cmd] action create
           - create user s3cmd


           ================================================================================
           Error executing action `create` on resource 'python_virtualenv[/home/s3cmd/.env2]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of ["/usr/bin/python2.7", "-m", "virtualenv", "/home/s3cmd/.env2"] ----
           STDOUT:
           STDERR: Traceback (most recent call last):
             File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
         File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
             File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2363, in <module>
        main()
             File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 832, in main
        symlink=options.symlink)
             File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 994, in create_environment
        site_packages=site_packages, clear=clear, symlink=symlink))
             File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1170, in install_python
        mkdir(lib_dir)
             File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 448, in mkdir
        os.makedirs(path)

        makedirs(head, mode)
             File "/usr/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
             File "/usr/lib/python2.7/os.py", line 150, in makedirs
        makedirs(head, mode)
             File "/usr/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
           OSError: [Errno 13] Permission denied: '/home/s3cmd'
       ---- End output of ["/usr/bin/python2.7", "-m", "virtualenv", "/home/s3cmd/.env2"] ----
           Ran ["/usr/bin/python2.7", "-m", "virtualenv", "/home/s3cmd/.env2"] returned 1
```

Is there anything I can do to help fix it?

**Comment by coderanger** [comment]
@jrake-revelant Please use `kitchen login` to SSH to the box and then run `sudo ls -la /home/s3cmd`.

**Comment by jrake-revelant** [comment]
I can't converge kitchen anymore since I am getting the same failure as in Travis: https://travis-ci.org/poise/poise-python/jobs/103535517

```
         * python_runtime_pip[2] action install


           * No candidate version available for setuptools
           ================================================================================
           Error executing action `install` on resource 'python_package[setuptools]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
           No candidate version available for setuptools

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
           /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:49:in `action_install'

           Resource Declaration:
       ---------------------
           # In /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb

           136:         python_package 'setuptools' do
           137:           parent_python new_resource
           138:           version setuptools_version if setuptools_version.is_a?(String)
           139:         end
           140:       end

**Comment by coderanger** [comment]
Yeah, the pip 8.0 release today break things. I'll fix it tomorrow.

**Comment by jrake-revelant** [comment]
No worries, I am suprised you are still up.

**Comment by jrake-revelant** [comment]
Is there a way to override it? I tried

```
python_runtime '2' do
	pip_version '7.1.2'
end

But it seems my `include_recipe 'poise-python'` is already causing the problem?

Cheers

**Comment by coderanger** [comment]
I haven't tested it yet and my brain is fading fast but if you set `node['poise-python']['options']['pip_version']` to `'7.1.2'` via a role, wrapper cookbook or anything else, it should take effect for all installed pythons. I'll put that up as a formal announcement in the morning when I can try it.

**Comment by coderanger** [comment]
You can also try:

```ruby
python_runtime_options '2' do
  pip_version '7.1.2'
end
```

in a wrapper or some other base recipe.

**Comment by bkw** [comment]
fyi, none of these workarounds worked for me.
Also: ohai @jrake-revelant :-)

**Comment by jrake-revelant** [comment]
First try with the following kitchen.yml failed, will try a wrapper:

```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[falcon-s3cmd::default]
    attributes:
       poise-python:
          options:
             pip-version: 7.1.2
```

**Comment by jrake-revelant** [comment]
```
python_runtime_options '2' do
  pip_version '7.1.2'
end
```

not working either, maybe I have some time later to look into a more verbose output and some of the code.

**Comment by bkw** [comment]
version 1.2.1 fixesthings for me, thanks!

**Comment by jrake-revelant** [comment]
I know I am late but thank you @coderanger for fixing this, it works as advertised :)
