### ISSUE TITLE
 Error executing action `install` on resource 'poise_languages_system[python3.4]'

### ISSUE THREAD

**Issue by jahrik** [poise/poise-python#20]
Hello,
I have been trying to work out this problem for a while now.  I have been testing this cookbook in vagrant and docker ubuntu 14.04.  All tests passed in vagrant and docker, but when I try it out on a lab server I get the following error.  Any ideas would be appriciated.  I am trying to upgrade our cookbooks from python to poise-python.

Thank you!

```
* python_runtime[python_runtime] action install
    * poise_languages_system[python3.4] action install
      
      ================================================================================
      Error executing action `install` on resource 'poise_languages_system[python3.4]'
      ================================================================================
      
      Chef::Exceptions::ValidationFailed
      ----------------------------------
      Option version must be a kind of [String]!  You passed [nil, nil].
      
      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:147:in `block in package_resources'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:146:in `tap'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:146:in `package_resources'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:162:in `run_package_action'
      /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:100:in `action_install'
      /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
      /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:44:in `action_install'
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb
      
       32:         poise_languages_system options['package_name'] || system_package_name do
       33:           # Otherwise use the default install action.
       34:           action(:upgrade) if options['package_upgrade']
       35:           parent new_resource
       36:           # Don't pass true because we want the default computed behavior for that.
       37:           dev_package options['dev_package'] unless options['dev_package'] == true
       38:           dev_package_overrides dev_package_overrides
       39:           package_version options['package_version'] if options['package_version']
       40:           version options['version']
       41:         end
       42:       end
      
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb:32:in `install_system_packages'
      
      poise_languages_system("python3.4") do
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :poise_languages_system
        cookbook_name "krs-log-archive"
        parent # Declared in /var/chef/cache/cookbooks/krs-log-archive/recipes/python_setup.rb:10:in `from_file'
      
      python_runtime("python_runtime") do
        provider PoisePython::PythonProviders::System
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        subresources [python_virtualenv[.env]]
        declared_type :python_runtime
        cookbook_name "krs-log-archive"
        recipe_name "python_setup"
        version "3"
        pip_version true
        setuptools_version true
        virtualenv_version true
        wheel_version true
      end
      
        version "3"
        package_name "python3.4"
        dev_package "python3.4-dev"
      end
      
    
    ================================================================================
    Error executing action `install` on resource 'python_runtime[python_runtime]'
    ================================================================================
    
    Chef::Exceptions::ValidationFailed
    ----------------------------------
    poise_languages_system[python3.4] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb line 32) had an error: Chef::Exceptions::ValidationFailed: Option version must be a kind of [String]!  You passed [nil, nil].
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:147:in `block in package_resources'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:146:in `tap'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:146:in `package_resources'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:162:in `run_package_action'
    /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:100:in `action_install'
    /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
    /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:44:in `action_install'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/krs-log-archive/recipes/python_setup.rb
    
     10: python_runtime 'python_runtime' do
     11:   provider :system
     12: 	version '3'
     13: 	pip_version true
     14: 	setuptools_version true
     15: 	virtualenv_version true
     16: 	wheel_version true
     17: end
     18:  
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/krs-log-archive/recipes/python_setup.rb:10:in `from_file'
    
    python_runtime("python_runtime") do
      provider PoisePython::PythonProviders::System
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      subresources [python_virtualenv[.env]]
      declared_type :python_runtime
      cookbook_name "krs-log-archive"
      recipe_name "python_setup"
      version "3"
      pip_version true
      setuptools_version true
      virtualenv_version true
      wheel_version true
    end
    

Running handlers:
[2015-12-08T06:39:06-07:00] ERROR: Running exception handlers
Running handlers complete
[2015-12-08T06:39:06-07:00] ERROR: Exception handlers complete
[2015-12-08T06:39:06-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 4 resources updated in 43.052575525 seconds
[2015-12-08T06:39:07-07:00] ERROR: python_runtime[python_runtime] (krs-log-archive::python_setup line 10) had an error: Chef::Exceptions::ValidationFailed: poise_languages_system[python3.4] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb line 32) had an error: Chef::Exceptions::ValidationFailed: Option version must be a kind of [String]!  You passed [nil, nil].
[2015-12-08T06:39:08-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by coderanger** [comment]
What version of Chef are you using? I would expect to see this on a version that predates multi-file support.

**Comment by coderanger** [comment]
If you can repro this on a recent version of Chef, please reopen.
