### ISSUE TITLE
Error executing action `install` on resource 'python_runtime[2]'

### ISSUE THREAD

**Issue by gretel** [poise/poise-python#23]
strongly suspecting new versions to bring up this issue; `ruby-2.3.0` running `chef-12.6`:
``` ================================================================================
         Error executing action `install` on resource 'python_runtime[2]'
         ================================================================================

         NoMethodError
         -------------
         NoMethodError

         Cookbook Trace:
         ---------------
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:125:in `response_file_variables'
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/lwrp_polyfill.rb:34:in `initialize'
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/resource_name.rb:32:in `initialize'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_package.rb:105:in `initialize'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:136:in `install_setuptools'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:51:in `block in action_install'
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
         /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
         /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:49:in `action_install'

         Resource Declaration:
         ---------------------
         # In /tmp/kitchen/cache/cookbooks/poise-python/recipes/default.rb

          20: python_runtime '2' if node['poise-python']['install_python2']

         Compiled Resource:
         ------------------
         # Declared in /tmp/kitchen/cache/cookbooks/poise-python/recipes/default.rb:20:in `from_file'

         python_runtime("2") do
           action [:install]
           retries 0
           retry_delay 2
           default_guard_interpreter :default
           subresources [python_runtime_pip[2]]
           declared_type :python_runtime
           cookbook_name "poise-python"
           recipe_name "default"
           pip_version true
           setuptools_version true
           version "2"
           virtualenv_version true
           wheel_version true
         end
```

**Comment by coderanger** [comment]
This was fixed in version 1.1.2.

**Comment by gretel** [comment]
@coderanger, 'Resolving cookbook dependencies with Berkshelf' comes up with version 1.1.1 and i was not expecting to have to change anything else.

**Comment by coderanger** [comment]
@gretel Run `berks update poise-python`.

**Comment by gretel** [comment]
did that, had to remove the lockfile for some reason. it's fine now, thanks!
