### ISSUE TITLE
Support for installing from private github repositories

### ISSUE THREAD

**Issue by eldenseropian** [poise/poise-python#30]
With the `python` cookbook, we could install from private git repositories like so:
```
include_recipe 'python'
python_pip 'git+ssh://git@github.com/Asana/asana-kinesis-python.git'
```

Attempting the equivalent with `python-poise`:
```
python_package 'git+ssh://git@github.com/Asana/asana-kinesis-python.git'
```
yields
```
---- Begin output of /usr/bin/python2.7 - list asanakinesis --outdated git\+ssh://git@github.com/Asana/asana-kinesis-python.git ----
       STDOUT:
       STDERR: The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
       /usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
         InsecurePlatformWarning
       You are using pip version 7.0.3, however version 8.0.0 is available.
       You should consider upgrading via the 'pip install --upgrade pip' command.
       Exception:
       Traceback (most recent call last):
         File "/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/basecommand.py", line 223, in main
           status = self.run(options, args)
         File "/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/commands/list.py", line 95, in run
           self.run_outdated(options)
         File "/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/commands/list.py", line 104, in run_outdated
           for dist, version, typ in self.find_packages_latest_versions(options):
         File "/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/commands/list.py", line 119, in find_packages_latest_versions
           user_only=options.user):
         File "<stdin>", line 18, in replacement
         File "/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
           reqs = list(parse_requirements(s))
         File "/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
           "version spec")
         File "/usr/local/lib/python2.7/dist-packages/pip-7.0.3-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
           raise ValueError(msg, line, "at", line[p:])
       ValueError: ('Expected version spec in', 'git+ssh://git@github.com/Asana/asana-kinesis-python.git', 'at', '+ssh://git@github.com/Asana/asana-kinesis-python.git')
       ---- End output of /usr/bin/python2.7 - list asanakinesis --outdated git\+ssh://git@github.com/Asana/asana-kinesis-python.git ----
       .7 - list asanakinesis --outdated git\+ssh://git@github.com/Asana/asana-kinesis-python.git returned 2
       [2016-01-20T22:28:42+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Is installing from private repositories supported in `poise-python`? Does it require different arguments?

**Comment by freeyoung** [comment]
I'm also wondering this...

**Comment by pecigonzalo** [comment]
@coderanger any progress on this?

**Comment by coderanger** [comment]
The `python_package` resource is not built for installing from directed sources as doing so is a non-idempotent action. My recommendation would be to either use a requirements file (and the corresponding resource) or a python_execute resource, in either case it makes things clear that it will be non-idempotent and you need to sort out the conditions.

An example of the execute form:

```ruby
python_execute '-m pip install git+ssh://git@github.com/Asana/asana-kinesis-python.git'
```

You'll have to handle configuring authentication yourself, though it may get wrapped up in the `application_git` cookbook at some point if you use that framework for things.

**Comment by coderanger** [comment]
Also to say the unhelpful-but-true grumpy FOSS thing, don't do that :) Running an internal package server can be as simple as an nginx server with autoindex turned on and a directory of wheels. That said, I'm sure you either have good reasons to do it this way or don't have the cycles to fix this this second, so the above should work fine. You probably don't actually need to care that it's non-idempotent even.
