### ISSUE TITLE
ImportError: No module named _vendor

### ISSUE THREAD

**Issue by jimbofreedman** [poise/poise-python#33]
I'm using the default python2.7 installation on Ubuntu 14.04 LTS

```python_package 'mopidy-moped'``` fails with: 
```
[2016-01-22T11:57:10+00:00] ERROR: python_package[mopidy-moped] (jackdaw::spotify line 81) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of ["/usr/bin/python", "-", "list", "--outdated", "mopidy-moped"] ----
STDOUT: Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 74, in run
    self.run_outdated(options)
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 83, in run_outdated
    for dist, remote_version_raw, remote_version_parsed in self.find_packages_latests_versions(options):
  File "/usr/lib/python2.7/dist-packages/pip/commands/list.py", line 108, in find_packages_latests_versions
    for dist in get_installed_distributions(local_only=options.local, skip=self.skip):
  File "<stdin>", line 13, in replacement
ImportError: No module named _vendor

Storing debug log for failure in /home/vagrant/.pip/pip.log
STDERR: 
---- End output of ["/usr/bin/python", "-", "list", "--outdated", "mopidy-moped"] ----
Ran ["/usr/bin/python", "-", "list", "--outdated", "mopidy-moped"] returned 2
```

Yet on the command line, all is fine:
```
vagrant@vagrant-ubuntu-trusty:~$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
vagrant@vagrant-ubuntu-trusty:~$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
vagrant@vagrant-ubuntu-trusty:~$ sudo pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
vagrant@vagrant-ubuntu-trusty:~$ sudo pip list --outdated mopidy-moped
argparse (Current: 1.2.1 Latest: 1.4.0)
setuptools (Current: 3.3 Latest: 19.4)
chardet (Current: 2.0.1 Latest: 2.3.0)
ssh-import-id (Current: 3.21 Latest: 4.5)
six (Current: 1.5.2 Latest: 1.10.0)
cffi (Current: 1.1.2 Latest: 1.5.0)
ply (Current: 3.4 Latest: 3.8)
requests (Current: 2.2.1 Latest: 2.9.1)
wheel (Current: 0.24.0 Latest: 0.26.0)
pycurl (Current: 7.19.3 Latest: 7.21.5)
pip (Current: 1.5.4 Latest: 8.0.2)
pycparser (Current: 2.10 Latest: 2.14)
html5lib (Current: 0.999 Latest: 0.9999999)
colorama (Current: 0.2.5 Latest: 0.3.6)
tornado (Current: 3.1.1 Latest: 4.3)
python-debian (Current: 0.1.21-nmu2ubuntu2 Latest: 0.1.23)
Could not find any downloads that satisfy the requirement apt-xapian-index
MySQL-python (Current: 1.2.3 Latest: 1.2.5)
urllib3 (Current: 1.7.1 Latest: 1.14)
vagrant@vagrant-ubuntu-trusty:~$ 
```

Am I misinterpreting what command is being run here? I feel like I'm missing what the resource is trying to do. I can provide my Vagrantfile and cookbook etc. if anybody would like more information.

**Comment by coderanger** [comment]
Please try with the latest poise-python.

**Comment by jimbofreedman** [comment]
````
---- Begin output of ["/usr/bin/python", "-", "mopidy-moped"] ----
STDOUT: 
STDERR: Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
ImportError: No module named _vendor
---- End output of ["/usr/bin/python", "-", "mopidy-moped"] ----
Ran ["/usr/bin/python", "-", "mopidy-moped"] returned 1
````
Now on poise-python 1.2.1 (sorry should have done that before).

**Comment by coderanger** [comment]
Hmm, I've not tested with pip 1.5.4, but it does have the relevant module (https://github.com/pypa/pip/blob/1.5.4/pip/_vendor/pkg_resources.py). That command comes before the install, used to check what versions of a package pip would install if asked.

**Comment by coderanger** [comment]
I do get an error with 1.5.4, but a different error:

```
Traceback (most recent call last):
  File "hack.py", line 20, in <module>
    format_control=options.format_control,
AttributeError: Values instance has no attribute 'format_control'
```

**Comment by coderanger** [comment]
Yeah, I don't think I can support anything less than pip 6.1.0, which is when the API to get all matches was added to `PackageFinder`. I can add error checking at least, but 1.5.4 is definitely not on my list.

Related: `python_runtime` should be automatically upgrading pip unless you told it not to.
