### ISSUE TITLE
Installing Python3 Not Functional on Ubuntu 15.10

### ISSUE THREAD

**Issue by mplanchard** [poise/poise-python#37]
Using hashicorp's ubuntu 15.10 box with Vagrant as the driver, I have been unable to get this cookbook to install Python 3. It seems to always fail on the `install` step. 

Currently I have the following defined in `poise-python.rb`:

```ruby
node.default['poise-python']['install_python2'] = false
node.default['poise-python']['install_python3'] = true
````

And I receive the following when trying to include the recipe:

````
       Recipe: poise-python::default
         * python_runtime[3] action install
           * poise_languages_system[python] action install
             
             ================================================================================
             Error executing action `install` on resource 'poise_languages_system[python]'
             ================================================================================
             
             PoiseLanguages::Error
             ---------------------
             Package python would install 2.7.9-1, which does not match 3. Please set the package_name or package_version provider options.
             
             Cookbook Trace:
             ---------------
             /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:192:in `block (4 levels) in patch_load_current_resource!'
             /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:190:in `block (3 levels) in patch_load_current_resource!'
             /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:189:in `tap'
             /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:189:in `block (2 levels) in patch_load_current_resource!'
             /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:172:in `block in run_package_action'
             /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:162:in `each'
       
             /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:100:in `action_install'
             /tmp/kitchen/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
             /tmp/kitchen/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:44:in `action_install'
             
             Resource Declaration:
             ---------------------
       # In /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb
             
       32:         poise_languages_system options['package_name'] || system_package_name do
       33:           # Otherwise use the default install action.
       34:           action(:upgrade) if options['package_upgrade']
       35:           parent new_resource
       36:           # Don't pass true because we want the default computed behavior for that.
        37:           dev_package options['dev_package'] unless options['dev_package'] == true
       38:           dev_package_overrides dev_package_overrides
       39:           package_version options['package_version'] if options['package_version']
       40:           version options['version']
       41:         end
       42:       end
             
             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb:32:in `install_system_packages'
             
             poise_languages_system("python") do
        action [:install]
        retries 0
       
        default_guard_interpreter :default
        declared_type :poise_languages_system
        cookbook_name :"poise-python"
        parent # Declared in /tmp/kitchen/cookbooks/poise-python/recipes/default.rb:19:in `from_file'
             
       
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :python_runtime
        cookbook_name :"poise-python"
        recipe_name "default"
        pip_version true
        setuptools_version true
        version "3"
        virtualenv_version true
        wheel_version true
             end
             
         version "3"
        package_name "python"
        dev_package "python-dev"
             end
             
           
           ================================================================================
           Error executing action `install` on resource 'python_runtime[3]'
           ================================================================================
           
           PoiseLanguages::Error
           ---------------------
       poise_languages_system[python] (/tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb line 32) had an error: PoiseLanguages::Error: Package python would install 2.7.9-1, which does not match 3. Please set the package_name or package_version provider options.
       
           Cookbook Trace:
           ---------------
       /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:192:in `block (4 levels) in patch_load_current_resource!'
           /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:190:in `block (3 levels) in patch_load_current_resource!'
           /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:189:in `tap'
           /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:189:in `block (2 levels) in patch_load_current_resource!'
           /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:172:in `block in run_package_action'
           /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:162:in `each'
           /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:162:in `run_package_action'
           /tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:100:in `action_install'
           /tmp/kitchen/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
           /tmp/kitchen/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:44:in `action_install'
       
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/poise-python/recipes/default.rb
           
            19: python_runtime '3' if node['poise-python']['install_python3']
            20: python_runtime '2' if node['poise-python']['install_python2']
           
           Compiled Resource:
           ------------------
       # Declared in /tmp/kitchen/cookbooks/poise-python/recipes/default.rb:19:in `from_file'
           
           python_runtime("3") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :python_runtime
             cookbook_name :"poise-python"
             recipe_name "default"
             pip_version true
             setuptools_version true
             version "3"
             virtualenv_version true
             wheel_version true
           end
           
       
       Running handlers:
       [2016-01-27T16:41:35+00:00] ERROR: Running exception handlers
       Running handlers complete
       
       
       [2016-01-27T16:41:35+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-01-27T16:41:35+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-01-27T16:41:35+00:00] ERROR: python_runtime[3] (poise-python::default line 19) had an error: PoiseLanguages::Error: poise_languages_system[python] (/tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb line 32) had an error: PoiseLanguages::Error: Package python would install 2.7.9-1, which does not match 3. Please set the package_name or package_version provider options.
       [2016-01-27T16:41:35+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
````

I have tried various combinations of specifying different runtime names, system package names, and versions, but have been unable to get it to work. Specifying a runtime with version 3.4 gives the same error message. Specifying the package name `python-3.4` for provider `:system` yields:

````
poise_languages_system[python-3.4] (/tmp/kitchen/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb line 32) had an error: PoiseLanguages::Error: Package python-3.4 would install , which does not match 3. Please set the package_name or package_version provider options.
````

**Comment by coderanger** [comment]
I only gave it package lists for the LTS versions: https://github.com/poise/poise-python/blob/master/lib/poise_python/python_providers/system.rb#L36

If you can grab the names of all python packages for that version, I can add them. You can also fix it locally via:

```ruby
python_runtime '3' do
  provider :system
  options package_name: 'python3.whatever'
end
```

**Comment by coderanger** [comment]
Closing this as 15.10 is no longer supported I think.

**Comment by jshthornton** [comment]
To get this working on ubuntu 16.04 LTS I had to use these settings:
```
provider :system
options package_name: 'python3', package_version: '3.5.1-3'
```
