### ISSUE TITLE
Softwarecollections.org is throwing 404 not found errors

### ISSUE THREAD

**Issue by eric-tucker** [poise/poise-python#44]
```
    ================================================================================
    Error executing action `install` on resource 'python_runtime[2]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    poise_languages_scl[python27] (/etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/mixin.rb line 27) had an error: Mixlib::ShellOut::ShellCommandFailed: rpm_package[rhscl-python27] (/etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb line 112) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
    ' https://www.softwarecollections.org/en/scls/rhscl/python27/fedora-21-x86_64/download/rhscl-python27-fedora-21-x86_64.noarch.rpm ----
    STDOUT: 
    STDERR: curl: (22) The requested URL returned error: 404 NOT FOUND
    error: open of https://www.softwarecollections.org/en/scls/rhscl/python27/fedora-21-x86_64/download/rhscl-python27-fedora-21-x86_64.noarch.rpm failed: No such file or directory
    ---- End output of rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
    ' https://www.softwarecollections.org/en/scls/rhscl/python27/fedora-21-x86_64/download/rhscl-python27-fedora-21-x86_64.noarch.rpm ----
    Ran rpm -qp --queryformat '%{NAME} %{VERSION}-%{RELEASE}
    ' https://www.softwarecollections.org/en/scls/rhscl/python27/fedora-21-x86_64/download/rhscl-python27-fedora-21-x86_64.noarch.rpm returned 1
    
    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
    /etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb:68:in `action_install'
    /etc/chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
    /etc/chef/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:44:in `action_install'

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/etucker/recipes/default.rb

     78: python_runtime "2"
     79:

    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/etucker/recipes/default.rb:78:in `from_file'

    python_runtime("2") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      subresources [python_package[astroid], python_package[awscli], python_package[awsebcli], python_package[aws-shell], python_package[boto3], python_package[docker-compose], python_package[docstring], python_package[ndg-httpsclient], python_package[pip], python_package[pyasn1], python_package[pyopenssl], python_package[pylint], python_package[s4cmd], python_package[wand], python_package[websocket], python_package[xkcdpass]]
      declared_type :python_runtime
      cookbook_name "etucker"
      recipe_name "default"
      pip_version true
      setuptools_version true
      version "2"
      virtualenv_version true
      wheel_version true
    end
```

Perhaps you an decipher?  Is Fedora 21 not supported by this cookbook?

**Comment by coderanger** [comment]
I think this is a dup of #43, which sounds like the Fedora packages were removed from SCL.
