### ISSUE TITLE
MemoryError during install package using pip

### ISSUE THREAD

**Issue by toracle** [poise/poise-python#46]
MemoryError occurs during install package using pip via 'python_package' directive.

I found pip's caching mechanism makes problem, [see this article](http://stackoverflow.com/a/31526029), so it would be fine if there is a kind of configuration not to use pip cache.

```
chef-test [2016-03-15T11:11:46-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out                                                                                                
chef-test [2016-03-15T11:11:46-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report                                                                         
chef-test [2016-03-15T11:11:46-04:00] ERROR: python_package[moin] (wiki::default line 19) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'    
chef-test ---- Begin output of ["/usr/bin/python2.7", "-m", "pip.__main__", "install", "moin==1.9.8"] ----                                                                                           
chef-test STDOUT: Collecting moin==1.9.8                                                                                                                                                             
chef-test   Downloading moin-1.9.8.tar.gz (37.1MB)                                                                                                                                                   
chef-test STDERR: Exception:                                                                                                                                                                         
chef-test Traceback (most recent call last):
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
chef-test     status = self.run(options, args)
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 310, in run
chef-test     wb.build(autobuilding=True)
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
chef-test     self.requirement_set.prepare_files(self.finder)
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
chef-test     ignore_dependencies=self.ignore_dependencies))
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 577, in _prepare_file
chef-test     session=self.session, hashes=hashes)
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 810, in unpack_url
chef-test     hashes=hashes
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 649, in unpack_http_url
chef-test     hashes)
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 871, in _download_http_url
chef-test     _download_url(resp, link, content_file, hashes)
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 595, in _download_url
chef-test     hashes.check_against_chunks(downloaded_chunks)
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
chef-test     for chunk in chunks:
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 563, in written_chunks
chef-test     for chunk in chunks:
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
chef-test     for x in it:
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 552, in resp_read
chef-test     decode_content=False):
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 344, in stream
chef-test     data = self.read(amt=amt, decode_content=decode_content)
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 301, in read
chef-test     data = self._fp.read(amt)
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
chef-test     self.__callback(self.__buf.getvalue())
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
chef-test     self.serializer.dumps(request, response, body=body),
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py", line 55, in dumps
chef-test     "body": _b64_encode_bytes(body),
chef-test   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py", line 12, in _b64_encode_bytes
chef-test     return base64.b64encode(b).decode("ascii")
chef-test MemoryError
```

I tried `pip install matplotlib` directly on the machine via ssh it fails, but when I try `pip --no-cache-dir install matplotlib` instead, it worked fine.

**Comment by coderanger** [comment]
What kind of machine are you using this on? That error was manifesting because it was a machine with very little RAM.

**Comment by coderanger** [comment]
You can try with:

```ruby
python_package 'moin' do
  options '--no-cache-dir'
end
```

**Comment by toracle** [comment]
Oh, python_package has options parameter also!

I used most small instance of DigitalOcean cloud hosting. It has 1 vCPU and 512M RAM.

It works well now with options parameter :)

**Comment by coderanger** [comment]
I would recommend setting up a swap file for your smaller instances.
