### ISSUE TITLE
RHE7 AWS AMI -->  python_runtime error

### ISSUE THREAD

**Issue by rschmidtz** [poise/poise-python#67]
Hi, I'm using the official AMI RHE7 from AWS and I'm getting the following errors:

```
Error executing action `install` on resource 'yum_package[python27]'
Error executing action `install` on resource 'poise_languages_scl[python27]'
Error executing action `install` on resource 'python_runtime[2]'
```

My recipe is simple:

```
include_recipe 'poise-python'

python_runtime '2'
python_virtualenv "#{node['django1.8']['path']}/venv"


python_package 'Django' do
  version '1.9'
end

package 'git' do
  action :install
end
```

The weird part is that testing in my local environment with kitchen in a centos7.2 box I don't have any problem.

**Comment by coderanger** [comment]
What's the actual error from yum? You may need to run with `chef-client -l debug` to see the debug output.

**Comment by rschmidtz** [comment]
```
     Chef::Exceptions::Exec
     ----------------------
     poise_languages_scl[python27] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/mixin.rb line 27) had an error: Chef::Exceptions::Exec: yum_package[python27] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb line 127) had an error: Chef::Exceptions::Exec: yum -d0 -e0 -y install python27-1.1-20.el7.centos returned 1:
     STDOUT:  You could try using --skip-broken to work around the problem
      You could try running: rpm -Va --nofiles --nodigest
     
     STDERR: Error: Package: python27-python-devel-2.7.8-3.el7.centos.x86_64 (rhscl-python27-epel-7-x86_64)
                Requires: scl-utils-build
     
     Cookbook Trace:
     ---------------
     /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
     /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb:68:in `action_install'
     /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
     /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:44:in `action_install'
     
     Resource Declaration:
     ---------------------
     # In /var/chef/cache/cookbooks/poise-python/recipes/default.rb
     
      20: python_runtime '2' if node['poise-python']['install_python2']
     
     Compiled Resource:
     ------------------
     # Declared in /var/chef/cache/cookbooks/poise-python/recipes/default.rb:20:in `from_file'
     
     python_runtime("2") do
       action [:install]
       updated true
       updated_by_last_action true
       retries 0
       retry_delay 2
       default_guard_interpreter :default
       declared_type :python_runtime
       cookbook_name "poise-python"
       recipe_name "default"
       pip_version true
       setuptools_version true
       version "2"
       virtualenv_version true
       wheel_version true
     end
     
     Platform:
     ---------
     x86_64-linux
     
```

**Comment by coderanger** [comment]
Hmm, much have shuffled some requirements in way that makes RHEL sad. I'm working on a revamp of the SCL installer code to better handle the new procedures from SCLo and RHSCL. For now you can use the `:system` provider which should be 2.7 on EL7 I think?

**Comment by rschmidtz** [comment]
The system provider is also failing 
```
python_runtime 'myapp' do
   provider :system
   version '2.7'
end
```

         ```
Error executing action `install` on resource 'yum_package[python27]'
         
         Chef::Exceptions::Exec
         ----------------------
         yum -d0 -e0 -y install python27-1.1-20.el7.centos returned 1:
         STDOUT:  You could try using --skip-broken to work around the problem
          You could try running: rpm -Va --nofiles --nodigest
         
         STDERR: Error: Package: python27-python-devel-2.7.8-3.el7.centos.x86_64 (rhscl-python27-epel-7-x86_64)
                    Requires: scl-utils-build
         
         Cookbook Trace:
         ---------------
         /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
         /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb:68:in `action_install'
         /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
         /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:44:in `action_install'
```

**Comment by coderanger** [comment]
That doesn't sound like the provider is getting set. You can see it still using the SCL code in the stack trace. Make sure you `knife upload`'d and whatnot? It should just install the package `python` in the end.

**Comment by rschmidtz** [comment]
looks weird, 

I did the knife upload, this is how my recipe looks like:
```
include_recipe 'poise-python'

python_runtime 'myapp' do
   provider :system
  version '2.7'
end

python_virtualenv "#{node['django1.8']['path']}/venv"
```
But I can notice that after the `include_recipe 'poise-python'` this happens:

```
Recipe: poise-python::default
* python_runtime[2] action install
```

And the `poise-python::default` looks like this:

```
# Default runtimes, last one will be the default.
python_runtime 'pypy' if node['poise-python']['install_pypy']
python_runtime '3' if node['poise-python']['install_python3']
python_runtime '2' if node['poise-python']['install_python2']
```

Isn't the `include_recipe 'poise-python'` automatically calling the `python_runtime` ?

**Comment by coderanger** [comment]
Ahh, you're crossing the streams. Generally you want either the `include_recipe` or your own use of `python_runtime`, not both. Your `python_runtime` is correct in this case, if you remove the include you should be fine. The issue is the runtime from the recipe is still using the default provider. If you want to use the recipe instead you could set `node['poise-python']['provider'] = 'system'` via any of the various ways to set attributes (role, env, wrapper, cookbook, etc).

**Comment by rschmidtz** [comment]
Great , thank's
