### ISSUE TITLE
Cannot override package_name in python_runtime resource

### ISSUE THREAD

**Issue by stevenhair** [poise/poise-python#70]
I'm using the [IUS](https://ius.io/) repositories for CentOS 7, which call their Python 3.5 package "python35u". I'm having trouble overriding the `package_name` in `python_runtime`.

```ruby
python_runtime '3.5' do
  provider :system
  version '3.5'
  package_name 'python35u'
end
```

results in:

```
==> default:   Running handlers:
==> default: [2016-08-31T16:39:39+00:00] ERROR: Running exception handlers
==> default:   Running handlers complete
==> default: [2016-08-31T16:39:39+00:00] ERROR: Exception handlers complete
==> default:   Chef Client failed. 1 resources updated in 11 seconds
==> default: [2016-08-31T16:39:39+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-08-31T16:39:39+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-08-31T16:39:39+00:00] ERROR: No resource or method named `package_name' for `PoisePython::Resources::PythonRuntime::Resource "3.5"'
```

Edit: So, I got a bit further:

```ruby
python_runtime '3.5.2' do
  provider :system
  options package_name: 'python35u-devel'
end
```

But now I get:

```
==> default: [2016-08-31T16:56:00+00:00] ERROR: python_runtime[3.5.2] (hs_web_auth::default line 84) had an error: NoMethodError: poise_languages_system[python35u-devel] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb line 32) had an error: NoMethodError: undefined method `start_with?' for nil:Chef::Decorator::Lazy
```

**Comment by coderanger** [comment]
Package name is an option (because it's specific to only certain providers) so you have to set it using one the ways you set options. In this case you probably want `options package_name: 'python35u'`

**Comment by coderanger** [comment]
Oh, you got that far, sorry github doesn't notify on edits.

**Comment by coderanger** [comment]
Full traceback on the error?

**Comment by stevenhair** [comment]
Full stack trace:

```
==> default:     ================================================================================
==> default:     Error executing action `install` on resource 'poise_languages_system[python35u-devel]'
==> default:     ================================================================================
==> default:
==> default:     NoMethodError
==> default:     -------------
==> default:     undefined method `start_with?' for nil:Chef::Decorator::Lazy
==> default:
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:192:in `block (4 levels) in patch_load_current_resource!'
==> default:     /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:191:in `block (3 levels) in patch_load_current_resource!'
==> default:     /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:190:in `tap'
==> default:     /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:190:in `block (2 levels) in patch_load_current_resource!'
==> default:     /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:173:in `block in run_package_action'
==> default:     /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:162:in `each'
==> default:     /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:162:in `run_package_action'
==> default:     /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:100:in `action_install'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:     /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
==> default:     /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:45:in `action_install'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb
==> default:
==> default:      32:         poise_languages_system system_package_name do
==> default:      33:           # Otherwise use the default install action.
==> default:      34:           action(:upgrade) if options['package_upgrade']
==> default:      35:           parent new_resource
==> default:      36:           # Don't pass true because we want the default computed behavior for that.
==> default:      37:           dev_package options['dev_package'] unless options['dev_package'] == true
==> default:      38:           dev_package_overrides dev_package_overrides
==> default:      39:           package_version options['package_version'] if options['package_version']
==> default:      40:           version options['version']
==> default:      41:         end
==> default:      42:       end
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb:32:in `install_system_packages'
==> default:
==> default:     poise_languages_system("python35u-devel") do
==> default:       action [:install]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :poise_languages_system
==> default:       cookbook_name "hs_web_auth"
==> default:       parent # Declared in /var/chef/cache/cookbooks/hs_web_auth/recipes/default.rb:85:in `from_file'
==> default:
==> default:     python_runtime("3.5.2") do
==> default:       provider PoisePython::PythonProviders::System
==> default:       action [:install]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       subresources [python_virtualenv[/opt/web-auth/venv/]]
==> default:       declared_type :python_runtime
==> default:       cookbook_name "hs_web_auth"
==> default:       recipe_name "default"
==> default:       options {"package_name"=>"python35u-devel"}
==> default:       get_pip_url "https://bootstrap.pypa.io/get-pip.py"
==> default:       pip_version true
==> default:       setuptools_version true
==> default:       version "3.5.2"
==> default:       virtualenv_version true
==> default:       wheel_version true
==> default:     end
==> default:
==> default:       version "3.5.2"
==> default:       package_name "python35u-devel"
==> default:       dev_package "python35u-devel-devel"
==> default:     end
==> default:
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
==> default:
==> default: [2016-08-31T19:21:09+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:
==> default:   ================================================================================
==> default:   Error executing action `install` on resource 'python_runtime[3.5.2]'
==> default:   ================================================================================
==> default:
==> default:   NoMethodError
==> default:   -------------
==> default:   poise_languages_system[python35u-devel] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb line 32) had an error: NoMethodError: undefined method `start_with?' for nil:Chef::Decorator::Lazy
==> default:
==> default:   Cookbook Trace:
==> default:   ---------------
==> default:   /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:192:in `block (4 levels) in patch_load_current_resource!'
==> default:   /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:191:in `block (3 levels) in patch_load_current_resource!'
==> default:   /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:190:in `tap'
==> default:   /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:190:in `block (2 levels) in patch_load_current_resource!'
==> default:   /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:173:in `block in run_package_action'
==> default:   /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:162:in `each'
==> default:   /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:162:in `run_package_action'
==> default:   /var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/resource.rb:100:in `action_install'
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:   /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
==> default:   /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:45:in `action_install'
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default:   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:
==> default:   Resource Declaration:
==> default:   ---------------------
==> default:   # In /var/chef/cache/cookbooks/hs_web_auth/recipes/default.rb
==> default:
==> default:    85: python_runtime '3.5.2' do
==> default:    86:   provider :system
==> default:    87:   options package_name: 'python35u-devel'
==> default:    88: end
==> default:    89:
==> default:
==> default:   Compiled Resource:
==> default:   ------------------
==> default:   # Declared in /var/chef/cache/cookbooks/hs_web_auth/recipes/default.rb:85:in `from_file'
==> default:
==> default:   python_runtime("3.5.2") do
==> default:     provider PoisePython::PythonProviders::System
==> default:     action [:install]
==> default:     retries 0
==> default:     retry_delay 2
==> default:     default_guard_interpreter :default
==> default:     subresources [python_virtualenv[/opt/web-auth/venv/]]
==> default:     declared_type :python_runtime
==> default:     cookbook_name "hs_web_auth"
==> default:     recipe_name "default"
==> default:     options {"package_name"=>"python35u-devel"}
==> default:     get_pip_url "https://bootstrap.pypa.io/get-pip.py"
==> default:     pip_version true
==> default:     setuptools_version true
==> default:     version "3.5.2"
==> default:     virtualenv_version true
==> default:     wheel_version true
==> default:   end
==> default:
==> default:   Platform:
==> default:   ---------
==> default:   x86_64-linux
==> default:
==> default: [2016-08-31T19:21:09+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:
==> default: Running handlers:
==> default: [2016-08-31T19:21:09+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-08-31T19:21:09+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 1 resources updated in 25 seconds
==> default: [2016-08-31T19:21:09+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-08-31T19:21:09+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-08-31T19:21:09+00:00] ERROR: python_runtime[3.5.2] (hs_web_auth::default line 85) had an error: NoMethodError: poise_languages_system[python35u-devel] (/var/chef/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/system/mixin.rb line 32) had an error: NoMethodError: undefined method `start_with?' for nil:Chef::Decorator::Lazy
==> default: [2016-08-31T19:21:10+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by coderanger** [comment]
What version of poise-python is this with? I thought I fixed that one a while ago: `unless candidate_version && candidate_version.start_with?(version)`

**Comment by stevenhair** [comment]
Sorry, should have mentioned that. I'm using 1.5.0

**Comment by coderanger** [comment]
Yeah, I think this is some new proxy objects getting returned, it's proxying for `nil` but isn't actually false-y itself so I need check `nil?` explicitly. Sigh. Will fix :)

**Comment by coderanger** [comment]
Also you probably don't want `-devel` in the package name, the provider does that internally.

**Comment by stevenhair** [comment]
Ah, that makes sense. New issue (not sure if I should open another issue):

```ruby
python_runtime '3.5.2' do
  provider :system
  options package_name: 'python35u' 
end
```

now produces this error:

```
==> default:   * python_runtime[3.5.2] action install
==> default:
==> default:     * poise_languages_system[python35u] action install
==> default:
==> default:        (up to date)
==> default:      (up to date)
==> default:    (up to date)
==> default:
==> default: ================================================================================
==> default: Error executing action `install` on resource 'python_runtime[3.5.2]'
==> default: ================================================================================
==> default:
==> default: Errno::ENOENT
==> default: -------------
==> default: No such file or directory - /usr/bin/python35u
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default: /var/chef/cache/cookbooks/poise/files/halite_gem/poise/utils/shell_out.rb:78:in `poise_shell_out'
==> default: /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:167:in `install_virtualenv'
==> default: /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:54:in `block in action_install'
==> default: /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
==> default: /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
==> default: /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
==> default: /var/chef/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:50:in `action_install'
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default: /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /var/chef/cache/cookbooks/hs_web_auth/recipes/default.rb
==> default:
==> default:  88: python_runtime '3.5.2' do
==> default:  89:   provider :system
==> default:  90:   options package_name: 'python35u'
==> default:  91: end
==> default:  92:
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /var/chef/cache/cookbooks/hs_web_auth/recipes/default.rb:88:in `from_file'
==> default:
==> default: python_runtime("3.5.2") do
==> default:   provider PoisePython::PythonProviders::System
==> default:   action [:install]
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   subresources [python_virtualenv[/opt/web-auth/venv/], python_runtime_pip[3.5.2], python_package[setuptools], python_package[wheel]]
==> default:   declared_type :python_runtime
==> default:   cookbook_name "hs_web_auth"
==> default:   recipe_name "default"
==> default:   options {"package_name"=>"python35u"}
==> default:   get_pip_url "https://bootstrap.pypa.io/get-pip.py"
==> default:   pip_version true
==> default:   setuptools_version true
==> default:   version "3.5.2"
==> default:   virtualenv_version true
==> default:   wheel_version true
==> default: end
==> default:
==> default: Platform:
==> default: ---------
==> default: x86_64-linux
==> default:
==> default: [2016-08-31T20:31:05+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:
==> default: Running handlers:
==> default: [2016-08-31T20:31:05+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-08-31T20:31:05+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 1 resources updated in 11 seconds
==> default: [2016-08-31T20:31:05+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-08-31T20:31:05+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-08-31T20:31:05+00:00] ERROR: python_runtime[3.5.2] (hs_web_auth::default line 88) had an error: Errno::ENOENT: No such file or directory - /usr/bin/python35u
```

and I don't see a way that I can set the path to the binary name like you can for the `dummy` provider.

**Comment by coderanger** [comment]
Yeah, that's just how the `system` provider works. It assumes the binary matches the package name. You probably want to make your own provider subclass if you want to tweak that.

```ruby
class MySystemProvider < PoisePython::PythonProviders::System
  provides(:my_system)
  def python_binary
    "/usr/bin/python" # Or whatever
  end
end
```

Throw that in a `libraries/default.rb` and change your resource to use it. Or tell whomever is making your packages that they should use the same structure as other packagers :)

**Comment by coderanger** [comment]
(a full fledged `:ius` provider would also be cool if you wanted to work on one to contribute)

**Comment by stevenhair** [comment]
So I fibbed a little bit, I'm not *actually* using IUS, just the IUS rpm in a private repository because internet access to the VMs in the UAT environment has been revoked. I'll take a look at it, though - my chef is good enough to get by, but that's about it. Getting into the weeds certainly couldn't hurt.

**Comment by coderanger** [comment]
@stevenhair It's also worth noting that the SCL packages are probably a better bet long term. I don't know what the future of IUS will be, but SCL has RedHat more explicitly behind it at this point.
