### ISSUE TITLE
Version 1.5 does not work on Amazon Linux

### ISSUE THREAD

**Issue by eric-tucker** [poise/poise-python#73]
Version 1.4.0 did.  I rebuilt my Chef package and brought in 1.5.1 today and now I'm failing with this stack trace:

```
Recipe: poise-python::default
  * python_runtime[2] action install
    * poise_languages_scl[python27] action install
      * yum_package[centos-release-scl-rh] action upgrade
        * No candidate version available for centos-release-scl-rh
        * No candidate version available for centos-release-scl-rh
        * No candidate version available for centos-release-scl-rh
        * No candidate version available for centos-release-scl-rh
        * No candidate version available for centos-release-scl-rh
        * No candidate version available for centos-release-scl-rh
        ================================================================================
        Error executing action `upgrade` on resource 'yum_package[centos-release-scl-rh]'
        ================================================================================
        
        Chef::Exceptions::Package
        -------------------------
        No candidate version available for centos-release-scl-rh
        
        Cookbook Trace:
        ---------------
        /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
        /etc/chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
        /etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb:71:in `action_install'
        /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
        /etc/chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
        /etc/chef/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:45:in `action_install'
        /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
        
        Resource Declaration:
        ---------------------
        # In /etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb
        
        114:           package 'centos-release-scl-rh' do
        115:             # Using upgrade here because changes very very rare and always
        116:             # important when they happen. If this breaks your prod infra, I'm
        117:             # sorry :-(
        118:             action :upgrade
        119:             retries 5
        120:           end
        121:         end
        
        Compiled Resource:
        ------------------
        # Declared in /etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb:114:in `install_scl_repo'
        
        yum_package("centos-release-scl-rh") do
          action [:upgrade]
          retries 5
          retry_delay 2
          default_guard_interpreter :default
          package_name "centos-release-scl-rh"
          flush_cache {:before=>false, :after=>false}
          declared_type :package
          cookbook_name "poise-python"
        end
        
      
      ================================================================================
      Error executing action `install` on resource 'poise_languages_scl[python27]'
      ================================================================================
      
      Chef::Exceptions::Package
      -------------------------
      yum_package[centos-release-scl-rh] (/etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb line 114) had an error: Chef::Exceptions::Package: No candidate version available for centos-release-scl-rh
      
      Cookbook Trace:
      ---------------
      /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
      /etc/chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
      /etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb:71:in `action_install'
      /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
      /etc/chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
      /etc/chef/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:45:in `action_install'
      /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
      
      Resource Declaration:
      ---------------------
      # In /etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/mixin.rb
      
       27:         poise_languages_scl options[:package_name] || pkg[:name] do
       28:           action :upgrade if options[:package_upgrade]
       29:           dev_package options[:dev_package] == true ? pkg[:devel_name] : options[:dev_package]
       30:           parent new_resource
       31:           version options[:package_version]
       32:         end
       33:       end
      
      Compiled Resource:
      ------------------
      # Declared in /etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/mixin.rb:27:in `install_scl_package'
      
      poise_languages_scl("python27") do
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :poise_languages_scl
        cookbook_name "poise-python"
        dev_package "python27-python-devel"
        parent # Declared in /etc/chef/local-mode-cache/cache/cookbooks/poise-python/recipes/default.rb:20:in `from_file'
      
      python_runtime("2") do
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        subresources [python_package[pip], python_package[virtualenv], python_package[boto3]]
        declared_type :python_runtime
        cookbook_name "poise-python"
        recipe_name "default"
        get_pip_url "https://bootstrap.pypa.io/get-pip.py"
        pip_version true
        setuptools_version true
        version "2"
        virtualenv_version true
        wheel_version true
      end
      
        package_name "python27"
      end
      
    
    ================================================================================
    Error executing action `install` on resource 'python_runtime[2]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    poise_languages_scl[python27] (/etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/mixin.rb line 27) had an error: Chef::Exceptions::Package: yum_package[centos-release-scl-rh] (/etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb line 114) had an error: Chef::Exceptions::Package: No candidate version available for centos-release-scl-rh
    
    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    /etc/chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
    /etc/chef/local-mode-cache/cache/cookbooks/poise-languages/files/halite_gem/poise_languages/scl/resource.rb:71:in `action_install'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    /etc/chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
    /etc/chef/local-mode-cache/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:45:in `action_install'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    
    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/poise-python/recipes/default.rb
    
     20: python_runtime '2' if node['poise-python']['install_python2']
    
    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/poise-python/recipes/default.rb:20:in `from_file'
    
    python_runtime("2") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      subresources [python_package[pip], python_package[virtualenv], python_package[boto3]]
      declared_type :python_runtime
      cookbook_name "poise-python"
      recipe_name "default"
      get_pip_url "https://bootstrap.pypa.io/get-pip.py"
      pip_version true
      setuptools_version true
      version "2"
      virtualenv_version true
      wheel_version true
    end
```

Amazon Linux version:
```
Linux ip-10-200-64-137 4.1.19-24.31.amzn1.x86_64 #1 SMP Tue Mar 15 23:41:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by coderanger** [comment]
Is Amazon Linux still under family `rhel`? I forget where we landed on that.

**Comment by coderanger** [comment]
I guess it must be given the code. Sigh.

**Comment by coderanger** [comment]
As an immediate workaround you can set it to the `system` provider (`provider :system` or `default['poise-python']['provider'] = 'system'` or whatevers).

**Comment by coderanger** [comment]
poise-languages 2.0.2 released with the fix.

**Comment by eric-tucker** [comment]
Lost notifications on this issue.  Amazon is rhel family, yes.  Thanks for the fix.
