### ISSUE TITLE
Subsequent Chef runs fail on setuptools on Ubuntu 16.04

### ISSUE THREAD

**Issue by luckymike** [poise/poise-python#80]
I've been seeing errors on Ubuntu 16.04 with subsequent chef runs failing after a successful first converge on `python_package[setuptools] action install` ([full gist](https://gist.github.com/luckymike/19a4cf0bc4abb7d78c01fd9bf94f34a5#file-gistfile1-txt-L1)):

```
  * python_package[setuptools] action install
    
    ================================================================================
    Error executing action `install` on resource 'python_package[setuptools]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of ["/usr/bin/python2.7", "-", "setuptools"] ----
    STDOUT: 
    STDERR: No handlers could be found for logger "pip.download"
    Traceback (most recent call last):
      File "<stdin>", line 38, in <module>
      File "/usr/local/lib/python2.7/dist-packages/pip/index.py", line 514, in find_requirement
        'No matching distribution found for %s' % req
    pip.exceptions.DistributionNotFound: No matching distribution found for setuptools
    ---- End output of ["/usr/bin/python2.7", "-", "setuptools"] ----
    Ran ["/usr/bin/python2.7", "-", "setuptools"] returned 1
```

I also have 14.04 systems that run the same code without issue. 

Our use is pretty vanilla, I think:
```
python_runtime '2.7'

python_virtualenv <py_home> do
  group <py_group>
  user <py_user>
end

execute 'update virtualenv permissions' do
  command "chown -R <py_user>:<py_group> <py_home>"
end
```
I welcome any suggestions to mitigate this.

Thanks!

**Comment by luckymike** [comment]
Update: as near as I can tell, this is only happening with interactive chef-client runs. Runs from a chef-client service or via test-kitchen seem fine, but `sudo chef-client` fails every time for me.

**Comment by coderanger** [comment]
@luckymike Any odd environment variables in your session?

**Comment by luckymike** [comment]
@coderanger nothing leaps out. We have some job specific vars à la `FB_AD_CLICK_SECRET` but nothing I'd expect to interfere with python.

**Comment by edupo** [comment]
Same here.
```
---- Begin output of ["/usr/bin/python3.5", "-", "setuptools"] ----
STDOUT:
STDERR: The directory '/home/air15884/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Could not find a version that satisfies the requirement setuptools (from versions: )
Traceback (most recent call last):
  File "<stdin>", line 38, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for setuptools
---- End output of ["/usr/bin/python3.5", "-", "setuptools"] ----
```
How can I set up pip to work with -H flag?
```
If executing pip with sudo, you may want sudo's -H flag.
```

**Comment by coderanger** [comment]
This is probably the same bug as #42, bad user/perm stuffs on non-root venvs.
