### ISSUE TITLE
No resource or method named `folder' in provider portable_pypy & portable_pypy3

### ISSUE THREAD

**Issue by patilarpith** [poise/poise-python#85]
According to the Readme file ```folder``` option can be used to specify the installation path. 

When I pass ```folder``` it always results in the error 

```
NoMethodError
-------------
No resource or method named `folder' for `PoisePython::Resources::PythonRuntime::Resource "pypy"'
```

**Installation command**
```
## Install PYPY 2
python_runtime 'pypy' do
  provider :portable_pypy
  version node[:pypy][:version]
  folder node[:pypy][:home]
end
```

**Error**
```
================================================================================
Recipe Compile Error in /home/ubuntu/chef-solo/local-mode-cache/cache/cookbooks/languages/recipes/default.rb
================================================================================

NoMethodError
-------------
No resource or method named `folder' for `PoisePython::Resources::PythonRuntime::Resource "pypy"'

Cookbook Trace:
---------------
  /home/ubuntu/chef-solo/local-mode-cache/cache/cookbooks/languages/recipes/default.rb:178:in `block in from_file'
  /home/ubuntu/chef-solo/local-mode-cache/cache/cookbooks/languages/recipes/default.rb:175:in `from_file'

Relevant File Content:
----------------------
/home/ubuntu/chef-solo/local-mode-cache/cache/cookbooks/languages/recipes/default.rb:

171:  end
172:  =end
173:
174:  ## Install PYPY 2
175:  python_runtime 'pypy' do
176:    provider :portable_pypy
177:    version node[:pypy][:version]
178>>   folder node[:pypy][:home]
179:  end
```

**Comment by coderanger** [comment]
Correct, `folder` is a provider option (meaning it only matters to specific providers) so it has to be passed via the options API.

```ruby
python_runtime 'pypy' do
  provider :portable_pypy
  version node[:pypy][:version]
  options folder: node[:pypy][:home]
end
```

**Comment by patilarpith** [comment]
@coderanger 

Even after passing location via options I see that pypy is still being setup at the default location

```
Recipe: languages::default
  * python_runtime[pypy] action install
    * poise_languages_static[/opt/pypy-5.6] action install
      * poise_archive[/home/ubuntu/chef-solo/local-mode-cache/cache/pypy-5.6-linux_x86_64-portable.tar.bz2] action nothing (skipped due to action :nothing)
      * remote_file[/home/ubuntu/chef-solo/local-mode-cache/cache/pypy-5.6-linux_x86_64-portable.tar.bz2] action create (up to date)
      * directory[/opt/pypy-5.6] action create
        - create new directory /opt/pypy-5.6
        - change mode from '' to '0755'
        - change owner from '' to '0'
        - change group from '' to '0'
      * poise_archive[/home/ubuntu/chef-solo/local-mode-cache/cache/pypy-5.6-linux_x86_64-portable.tar.bz2] action unpack
        * directory[/opt/pypy-5.6] action create (up to date)
        * apt_package[tar, bzip2] action install (up to date)
        - unpack archive /home/ubuntu/chef-solo/local-mode-cache/cache/pypy-5.6-linux_x86_64-portable.tar.bz2 to /opt/pypy-5.6
```
