### ISSUE TITLE
Virtualenv library error when using scl and a non-root chef run

### ISSUE THREAD

**Issue by parak** [poise/poise-python#87]
Hi,

Using test-kitchen with some patches I'm currently running application tests where a root run happens first, and then another more limited chef run happens as a generic user of that application. The root chef run works fine, creating and managing the virtualenv under said generic user without any issues - it's only when the non-root run happens against this previously root created virtualenv does it error out (with slightly obfuscated paths):

```
         * python_virtualenv[/home/someuser/somepath/virtualenv] action create
           * python_runtime_pip[/home/someuser/somepath/virtualenv] action install
             
             ================================================================================
             Error executing action `install` on resource 'python_runtime_pip[/home/someuser/somepath/virtualenv]'
             ================================================================================
             
             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '127'
             ---- Begin output of ["/home/someuser/somepath/virtualenv/bin/python", "/tmp/get-pip20170317-20312-q4ay5c.py", "--upgrade", "--force-reinstall"] ----
             STDOUT: 
             STDERR: /home/someuser/somepath/virtualenv/bin/python: error while loading shared libraries: libpython3.4m.so.rh-python34-1.0: cannot open shared object file: No such file or directory
             ---- End output of ["/home/someuser/somepath/virtualenv/bin/python", "/tmp/get-pip20170317-20312-q4ay5c.py", "--upgrade", "--force-reinstall"] ----
             Ran ["/home/someuser/somepath/virtualenv/bin/python", "/tmp/get-pip20170317-20312-q4ay5c.py", "--upgrade", "--force-reinstall"] returned 127
             
             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/utils/shell_out.rb:86:in `tap'
             /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/utils/shell_out.rb:86:in `poise_shell_out!'
             /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime_pip.rb:125:in `block in bootstrap_pip'
             /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime_pip.rb:106:in `bootstrap_pip'
             /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/resources/python_runtime_pip.rb:83:in `action_install'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
             /tmp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
             /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:50:in `action_install'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
             
             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb
             
             118:         python_runtime_pip new_resource.name do
             119:           parent new_resource
             120:           # If the version is `true`, don't pass it at all.
             121:           version pip_version if pip_version.is_a?(String)
             122:           get_pip_url pip_url
             123:         end
             124:       end
             125: 
             
             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/poise-python/files/halite_gem/poise_python/python_providers/base.rb:118:in `install_pip'
             
             python_runtime_pip("/home/someuser/somepath/virtualenv") do
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :python_runtime_pip
        cookbook_name "some-cookbook"
        parent python_virtualenv[/home/someuser/somepath/virtualenv]
        get_pip_url "https://bootstrap.pypa.io/get-pip.py"
             end
             
             Platform:
             ---------
             x86_64-linux

```

This is on CentOS 6.8 with 3.4 from scl, with chef running as 'sudo -u someuser <chef-client..>'. If I manually (interactively) enable scl, the virtualenv works fine under that user as expected. The actual resource (which again works fine in a root user chef run) is fairly basic:

```
  python_virtualenv "/home/someuser/somepath/virtualenv" do
    python '3.4'
    user 'someuser'
    action :create
  end
```

At first I thought that it was somehow due to issue [42](https://github.com/poise/poise-python/issues/42), but after manual chowning it's still the same. Not quite sure if I'm doing something wrong, as I'm fairly new to the cookbook after migrating from the deprecated one (where this wasn't a problem although with 2.7). Thanks!

**Comment by coderanger** [comment]
Probably still some bad permissions, but this is not something I'm going to test myself so you'll have to do the legwork to track it down. This is not how Chef is intended to be used.

**Comment by coderanger** [comment]
Specifically make sure your user has `+rx` on all the directories leading up to that file.

**Comment by parak** [comment]
But Chef specifically [mentions](https://docs.chef.io/ctl_chef_client.html#run-as-non-root-user) being able to run it as non root in its documentation, with caveats that I'm well familiar with.

Yep, user has rwx on all dirs from home to the virtualenv, including. Chowning everything to the user is done during the root run, as well. I ran into the library issue before (as root), but just on execute resources and such, and they were fixed by changing them to python_execute instead with the virtualenv property. This seems different to me as it fails on the python_virtualenv resource itself which I understand should be able to link the library.

Not much else for me to dig around for this it seems.. I did a workaround instead where the resource only runs if uid is 0. It's far from ideal, however.

**Comment by coderanger** [comment]
Might be something funky with the dynamic linker cache? SCL packages are odd in that they don't include an `rpath` value compiled in to the executable, so my code (and `scl enable` if running from the CLI) has to set `$LD_LIBRARY_PATH` so things are visible to the linker. Does the same thing happen if using system packages?
